# Generated by Django 2.2 on 2019-04-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0003_auto_20190409_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='nationality',
            new_name='specialty',
        ),
    ]
