# Generated by Django 2.2 on 2019-04-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0005_auto_20190410_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='preview_url',
        ),
        migrations.AddField(
            model_name='patient',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(default='/ /', max_length=100),
        ),
    ]
