# Generated by Django 2.2 on 2019-04-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0008_auto_20190411_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='title',
            field=models.CharField(default="patient's full name", max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
