# Generated by Django 2.2 on 2019-04-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0010_auto_20190411_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AlterField(
            model_name='patient',
            name='title',
            field=models.CharField(default="patient's name", max_length=100),
        ),
    ]
