# Generated by Django 2.2 on 2019-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0011_auto_20190411_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.CharField(default='description, or symptoms of illness', max_length=200),
        ),
    ]
