# Generated by Django 2.2 on 2019-04-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0012_auto_20190412_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='title',
        ),
    ]
