# Generated by Django 2.2 on 2019-04-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0013_auto_20190412_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='next_of_kin',
            new_name='next_of_Kin',
        ),
    ]
