# Generated by Django 2.2 on 2019-04-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0014_auto_20190412_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(default="patient's date of birth", max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(default="today's date", max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.CharField(default='time of appointment', max_length=100),
        ),
    ]
