# Generated by Django 2.2 on 2019-04-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0015_auto_20190412_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='date_of_Birth',
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(default="doctor's physical address", max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default="doctor's phone number", max_length=100),
        ),
    ]
