# Generated by Django 2.2 on 2019-04-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0016_auto_20190412_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photo_url',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
